### ISSUE TITLE
When the ziti-tunnel service is not running the UI cannot be closed - only quit

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-tunnel-win#33]
![image](https://user-images.githubusercontent.com/46322585/84581644-80cda980-adb1-11ea-9bf4-91f8442d009c.png)

clicking off the window won't hide the app. other windows can appear over the UI but this window can't be dismissed

**Comment by JeremyTellier** [comment]
This is the expected behavior, you can navigate away and it will minimize to tray. Functionality of the UI is disabled until the service is available otherwise everything would just be error after error.

**Comment by dovholuknf** [comment]
I should not be able to take this screen cap then, right? i've not seen this functionality before 
![image](https://user-images.githubusercontent.com/46322585/84778364-e50a8c00-afb0-11ea-93d6-34f0a2739f3e.png)
