### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/ziti-tunnel-win#35]
Identities take a long time to turn on, need an indeterminate loading screen for long running operations like this.

**Comment by dovholuknf** [comment]
i still don't see any spinner when loading an identity. the timeout seems shorter though - was that the fix? gif showing no spinner attached

![no-spinner](https://user-images.githubusercontent.com/46322585/84826595-2b7fdb00-aff1-11ea-9196-067378ecb6ec.gif)

**Comment by dovholuknf** [comment]
opened https://github.com/openziti/ziti-tunnel-win/issues/39 to track this instead of this issue
