### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/ziti-tunnel-win#36]
Random Network crashes, also rebooted Windows after an "Add identity" when already in Error state

**Comment by dovholuknf** [comment]
if the service stops again - please upload the cziti.log as well as the ziti-tunneler.log from C:\Windows\System32\config\systemprofile\AppData\Roaming\NetFoundry

**Comment by dovholuknf** [comment]
i think the latest tunneler branch will fix this. i've not seen any 'random crashing' lately and i'm not able to crash it intentionally any more via iperf (i used to be able to)

closing for now due to that. we can open it back up again if needed
