### ISSUE TITLE
Invalid JSON Error

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/ziti-tunnel-win#37]
Service returns Invalid JSON after adding a new identity and does not load.

Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Invalid character after parsing property name. Expected ':' but got: M. Path 'Status.Identities[0].Services[2]', line 1, position 443.

**Comment by dovholuknf** [comment]
what version does the service report? Also can you reproduce this issue? I haven't seen it yet. I'll need steps to reproduce to debug it. closing for now -reopen if you have steps to reproduce pls
